
-- Create tables
CREATE TABLE YPERSON
   (PERSONID NUMBER(15,0) NOT NULL,
    FIRSTNAME VARCHAR2(15) NOT NULL,
    MIDDLENAME VARCHAR2(15) NULL,
    LASTNAME VARCHAR2(15) NOT NULL,
    USERID VARCHAR2(15) NOT NULL,
    PASSWORD VARCHAR2(10) NOT NULL,
    ADDRESSID NUMBER(15,0) NULL);

ALTER TABLE YPERSON
   ADD CONSTRAINT PERSONPK PRIMARY KEY (PERSONID);
